name: Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build
        shell: bash
        run: dotnet publish Downloader/Downloader.csproj --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "${{ matrix.os }}"
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}